# Generated by Django 4.2.2 on 2023-06-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_actor_director_slug_movie_avg_rating_movie_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='films.actor'),
        ),
    ]
